#!/usr/bin/env bash
# ============================================================================
# Nexum Phase 7 (Hardening) - Part 3: structured logging + thin Sentry capture
#
# Stops losing failures. Adds a zero-dependency structured logger and an error
# capture path that ships to Sentry ONLY when SENTRY_DSN is set (inert
# otherwise), then routes the highest-value silent-failure points through it:
#
#   NEW  nexum-api/src/lib/logger.ts     log.{debug,info,warn,error} + captureException + installGlobalErrorCapture
#   NEW  nexum-api/tests/logger.test.ts  7 tests (structured output, DSN ship, never-throws)
#   PATCH errorHandler.ts  - unhandled route errors captured with stack + method/path (no body -> no PII)
#   PATCH index.ts         - installGlobalErrorCapture() at startup (unhandledRejection / uncaughtException)
#   PATCH payroll.ts       - runBatchPayout(...).catch(() => {}) now captures instead of swallowing a failed payout run
#
# Dependency-light by choice: no @sentry SDK, no transitive deps. Sentry uses
# its plain HTTP ingest API. With no SENTRY_DSN, behaviour is unchanged except
# logs become structured JSON and previously-silent errors now log.
#
# CONFIG (all optional):
#   SENTRY_DSN   enable Sentry shipping (e.g. https://<key>@<host>/<projectId>)
#   LOG_LEVEL    debug|info|warn|error   (default info)
#   APP_VERSION  release label sent to Sentry (default npm_package_version or 'dev')
#
# Delivery contract (v2) + full deploy:
#   * payloads base64 + sha256 verified; exact-anchor patch; aborts on drift
#   * idempotent (marker __NEXUM_OBSERVABILITY_WIRED__); clean-only backups
#   * gate: tsc --noEmit -> vitest run -> commit + push
#   * --revert restores the 3 patched files + removes logger + its test
#   * --no-deploy applies + verifies only
#
# Run from REPO ROOT (folder containing nexum-api/).
#   bash nexum-phase7-part3-observability.sh
#   bash nexum-phase7-part3-observability.sh --no-deploy
#   bash nexum-phase7-part3-observability.sh --revert
# ============================================================================
set -euo pipefail

API="nexum-api"
LOGGER="$API/src/lib/logger.ts"
LOGGER_TEST="$API/tests/logger.test.ts"
EH="$API/src/middleware/errorHandler.ts"
IDX="$API/src/index.ts"
PAYROLL="$API/src/routes/payroll.ts"
MARKER="__NEXUM_OBSERVABILITY_WIRED__"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP_DIR=".nexum-phase7p3-backup/${STAMP}"
LOG_SHA="b641b983a274e38dd944d2d4cd0823e0a1e4a5fd26cca7a67585713c42175b47"; TEST_SHA="7be159ccf3daba6c287fdc79aeddd70ce7c69c813b5f36cf7a0b812f032aac7a"; PATCH_SHA="3a34dedd6e7a2b3c04613796731b795164a67affef3690ac8f1806a1f03cd537"
COMMIT_MSG="feat(api): structured logging + thin Sentry capture; surface swallowed failures (Phase 7.3)"

FLAG="${1:-}"
log(){ printf '  %s\n' "$*"; }
die(){ printf 'ERROR: %s\n' "$*" >&2; exit 1; }

[ -d "$API" ] || die "Cannot find $API . Run from the repo root."

if [ "$FLAG" = "--revert" ]; then
  LATEST=""
  for d in $(ls -1dt .nexum-phase7p3-backup/*/ 2>/dev/null); do
    if [ -f "${d}errorHandler.ts" ] || [ -f "${d}index.ts" ] || [ -f "${d}payroll.ts" ]; then LATEST="$d"; break; fi
  done
  if [ -n "$LATEST" ]; then
    [ -f "${LATEST}errorHandler.ts" ] && cp "${LATEST}errorHandler.ts" "$EH"      && log "Restored $EH"
    [ -f "${LATEST}index.ts" ]        && cp "${LATEST}index.ts"        "$IDX"     && log "Restored $IDX"
    [ -f "${LATEST}payroll.ts" ]      && cp "${LATEST}payroll.ts"      "$PAYROLL" && log "Restored $PAYROLL"
  else
    log "No backup found; leaving patched files as-is."
  fi
  rm -f "$LOGGER" && log "Removed $LOGGER"
  rmdir "$API/src/lib" 2>/dev/null || true
  rm -f "$LOGGER_TEST" && log "Removed $LOGGER_TEST"
  log "Reverted Phase 7 Part 3."
  exit 0
fi

TLOG="$(mktemp)"; TTEST="$(mktemp)"; TPATCH="$(mktemp /tmp/p7p3.XXXXXX.py)"
trap 'rm -f "$TLOG" "$TTEST" "$TPATCH"' EXIT

base64 -d > "$TLOG" <<'B64LOG'
Ly8gX19ORVhVTV9PQlNFUlZBQklMSVRZX18gKHBoYXNlNykgc3RydWN0dXJlZCBsb2dnaW5nICsg
dGhpbiBTZW50cnkgY2FwdHVyZQovLwovLyBQaGFzZSA3IEhhcmRlbmluZy4gVHdvIGpvYnMsIHpl
cm8gZGVwZW5kZW5jaWVzOgovLwovLyAgIGxvZy57ZGVidWcsaW5mbyx3YXJuLGVycm9yfShtc2cs
IGZpZWxkcz8pICAtIHN0cnVjdHVyZWQgSlNPTiB0byBzdGRvdXQvc3RkZXJyCi8vICAgY2FwdHVy
ZUV4Y2VwdGlvbihlcnIsIGNvbnRleHQ/KSAgICAgICAgICAgIC0gc2hpcCBhbiBlcnJvciB0byBT
ZW50cnkgSUYgYQovLyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgIFNFTlRSWV9EU04gaXMgY29uZmlndXJlZDsgZWxzZQovLyAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgICAgIGl0IGp1c3QgbG9ncy4gTmV2ZXIgdGhyb3dzLgov
LwovLyBXaHkgaG9tZS1ncm93bjogdGhlIHJvYWRtYXAgYXNrcyBmb3IgInN0cnVjdHVyZWQgbG9n
Z2luZyArIFNlbnRyeSIgYnV0IHRoZQovLyBwcm9qZWN0IGRlbGliZXJhdGVseSBrZWVwcyBkZXBl
bmRlbmNpZXMgbWluaW1hbCBhbmQgY29udHJvbGxlZC4gVGhpcyBnaXZlcwovLyBKU09OIGxvZ3Mg
KGdyZXBwYWJsZSwgaW5nZXN0aWJsZSBieSBhbnkgbG9nIHBsYXRmb3JtKSBhbmQgZXJyb3IgY2Fw
dHVyZSB2aWEKLy8gU2VudHJ5J3MgcGxhaW4gSFRUUCBpbmdlc3QgQVBJIC0gbm8gU0RLLCBubyB0
cmFuc2l0aXZlIGRlcHMsIGFuZCBpdCBpcyBpbmVydAovLyB1bmxlc3MgU0VOVFJZX0RTTiBpcyBz
ZXQsIHNvIGxvY2FsL2RldiBiZWhhdmlvdXIgaXMgdW5jaGFuZ2VkLgovLwovLyBUaGUgcG9pbnQg
b2YgdGhpcyBwYXJ0IGlzIHRvIHN0b3AgbG9zaW5nIGZhaWx1cmVzLiBTaWxlbnQgYGNhdGNoIHt9
YCBhbmQKLy8gZmlyZS1hbmQtZm9yZ2V0IGAuY2F0Y2goKCkgPT4ge30pYCBzd2FsbG93IGV4YWN0
bHkgdGhlIGVycm9ycyB0aGF0IGNvc3QgdXMKLy8gcmVhbCBkZWJ1Z2dpbmcgdGltZSAodGhlIGZy
YWN0aW9uYWwtYnBzIGNyYXNoIGhpZCB0aGlzIHdheSkuIFJvdXRlIHRob3NlCi8vIHRocm91Z2gg
Y2FwdHVyZUV4Y2VwdGlvbiBpbnN0ZWFkIGFuZCB0aGV5IHN1cmZhY2UuCgp0eXBlIExldmVsID0g
J2RlYnVnJyB8ICdpbmZvJyB8ICd3YXJuJyB8ICdlcnJvcicKCmNvbnN0IFNFUlZJQ0UgICAgID0g
J25leHVtLWFwaScKY29uc3QgRU5WICAgICAgICAgPSBwcm9jZXNzLmVudi5OT0RFX0VOViA/PyAn
ZGV2ZWxvcG1lbnQnCmNvbnN0IFJFTEVBU0UgICAgID0gcHJvY2Vzcy5lbnYuQVBQX1ZFUlNJT04g
Pz8gcHJvY2Vzcy5lbnYubnBtX3BhY2thZ2VfdmVyc2lvbiA/PyAnZGV2Jwpjb25zdCBTRU5UUllf
RFNOICA9IHByb2Nlc3MuZW52LlNFTlRSWV9EU04gPz8gJycKY29uc3QgTUlOX0xFVkVMICAgPSAo
cHJvY2Vzcy5lbnYuTE9HX0xFVkVMIGFzIExldmVsKSA/PyAnaW5mbycKCmNvbnN0IExFVkVMX1JB
Tks6IFJlY29yZDxMZXZlbCwgbnVtYmVyPiA9IHsgZGVidWc6IDEwLCBpbmZvOiAyMCwgd2Fybjog
MzAsIGVycm9yOiA0MCB9CgpmdW5jdGlvbiBlbWl0KGxldmVsOiBMZXZlbCwgbWVzc2FnZTogc3Ry
aW5nLCBmaWVsZHM/OiBSZWNvcmQ8c3RyaW5nLCB1bmtub3duPikgewogIGlmIChMRVZFTF9SQU5L
W2xldmVsXSA8IExFVkVMX1JBTktbTUlOX0xFVkVMXSkgcmV0dXJuCiAgY29uc3QgbGluZSA9IHsK
ICAgIHRzOiAgICAgIG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKSwKICAgIGxldmVsLAogICAgc2Vy
dmljZTogU0VSVklDRSwKICAgIGVudjogICAgIEVOViwKICAgIG1zZzogICAgIG1lc3NhZ2UsCiAg
ICAuLi4oZmllbGRzID8/IHt9KSwKICB9CiAgLy8gSlNPTiBvbiBvbmUgbGluZTogcGFyc2VhYmxl
IGJ5IGFueSBsb2cgcGxhdGZvcm0sIHN0aWxsIHJlYWRhYmxlIGluIGEgdGFpbC4KICBjb25zdCBv
dXQgPSBKU09OLnN0cmluZ2lmeShsaW5lKQogIGlmIChsZXZlbCA9PT0gJ2Vycm9yJyB8fCBsZXZl
bCA9PT0gJ3dhcm4nKSBjb25zb2xlLmVycm9yKG91dCkKICBlbHNlIGNvbnNvbGUubG9nKG91dCkK
fQoKZXhwb3J0IGNvbnN0IGxvZyA9IHsKICBkZWJ1ZzogKG06IHN0cmluZywgZj86IFJlY29yZDxz
dHJpbmcsIHVua25vd24+KSA9PiBlbWl0KCdkZWJ1ZycsIG0sIGYpLAogIGluZm86ICAobTogc3Ry
aW5nLCBmPzogUmVjb3JkPHN0cmluZywgdW5rbm93bj4pID0+IGVtaXQoJ2luZm8nLCBtLCBmKSwK
ICB3YXJuOiAgKG06IHN0cmluZywgZj86IFJlY29yZDxzdHJpbmcsIHVua25vd24+KSA9PiBlbWl0
KCd3YXJuJywgbSwgZiksCiAgZXJyb3I6IChtOiBzdHJpbmcsIGY/OiBSZWNvcmQ8c3RyaW5nLCB1
bmtub3duPikgPT4gZW1pdCgnZXJyb3InLCBtLCBmKSwKfQoKLy8g4pSA4pSAIFNlbnRyeSBEU04g
cGFyc2luZyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi
lIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDi
lIDilIDilIAKLy8gQSBEU04gbG9va3MgbGlrZTogaHR0cHM6Ly88cHVibGljS2V5PkA8aG9zdD4v
PHByb2plY3RJZD4KLy8gVGhlIGluZ2VzdCBlbmRwb2ludCBpczogIGh0dHBzOi8vPGhvc3Q+L2Fw
aS88cHJvamVjdElkPi9zdG9yZS8KLy8gd2l0aCBhbiBYLVNlbnRyeS1BdXRoIGhlYWRlciBjYXJy
eWluZyB0aGUgcHVibGljIGtleS4gV2UgYnVpbGQgdGhpcyBieSBoYW5kCi8vIHNvIHdlIG5lZWQg
bm8gU0RLLgppbnRlcmZhY2UgUGFyc2VkRHNuIHsgZW5kcG9pbnQ6IHN0cmluZzsgcHVibGljS2V5
OiBzdHJpbmcgfQpmdW5jdGlvbiBwYXJzZURzbihkc246IHN0cmluZyk6IFBhcnNlZERzbiB8IG51
bGwgewogIHRyeSB7CiAgICBjb25zdCB1ID0gbmV3IFVSTChkc24pCiAgICBjb25zdCBwcm9qZWN0
SWQgPSB1LnBhdGhuYW1lLnJlcGxhY2UoL15cLy8sICcnKQogICAgaWYgKCF1LnVzZXJuYW1lIHx8
ICFwcm9qZWN0SWQpIHJldHVybiBudWxsCiAgICByZXR1cm4gewogICAgICBlbmRwb2ludDogIGAk
e3UucHJvdG9jb2x9Ly8ke3UuaG9zdH0vYXBpLyR7cHJvamVjdElkfS9zdG9yZS9gLAogICAgICBw
dWJsaWNLZXk6IHUudXNlcm5hbWUsCiAgICB9CiAgfSBjYXRjaCB7IHJldHVybiBudWxsIH0KfQpj
b25zdCBEU04gPSBTRU5UUllfRFNOID8gcGFyc2VEc24oU0VOVFJZX0RTTikgOiBudWxsCgovKgog
IENhcHR1cmUgYW4gZXJyb3IuIEFsd2F5cyBsb2dzIGl0IChzbyBub3RoaW5nIGlzIGxvc3QgZXZl
biB3aXRob3V0IFNlbnRyeSksIGFuZAogIGFkZGl0aW9uYWxseSBzaGlwcyBpdCB0byBTZW50cnkg
d2hlbiBjb25maWd1cmVkLiBGaXJlLWFuZC1mb3JnZXQgYnkgZGVzaWduIC0KICBpdCBuZXZlciB0
aHJvd3MgYW5kIG5ldmVyIGJsb2NrcyB0aGUgY2FsbGVyLCBiZWNhdXNlIGNhcHR1cmluZyBhbiBl
cnJvciBtdXN0CiAgbm90IGl0c2VsZiBicmVhayBhIHJlcXVlc3Qgb3IgYSBqb2IuCiovCmV4cG9y
dCBmdW5jdGlvbiBjYXB0dXJlRXhjZXB0aW9uKAogIGVycjogdW5rbm93biwKICBjb250ZXh0Pzog
UmVjb3JkPHN0cmluZywgdW5rbm93bj4sCik6IHZvaWQgewogIGNvbnN0IGUgPSBlcnIgaW5zdGFu
Y2VvZiBFcnJvciA/IGVyciA6IG5ldyBFcnJvcihTdHJpbmcoZXJyKSkKCiAgLy8gQWx3YXlzIGxv
ZyAtIHRoaXMgaXMgdGhlIHBhcnQgdGhhdCBndWFyYW50ZWVzIHRoZSBmYWlsdXJlIGlzIHZpc2li
bGUuCiAgbG9nLmVycm9yKGUubWVzc2FnZSwgewogICAgZXJyOiAgIGUubmFtZSwKICAgIHN0YWNr
OiBlLnN0YWNrLAogICAgLi4uKGNvbnRleHQgPz8ge30pLAogIH0pCgogIGlmICghRFNOKSByZXR1
cm4KCiAgY29uc3QgZXZlbnQgPSB7CiAgICBldmVudF9pZDogIGNyeXB0by5yYW5kb21VVUlEKCku
cmVwbGFjZSgvLS9nLCAnJyksCiAgICB0aW1lc3RhbXA6IG5ldyBEYXRlKCkudG9JU09TdHJpbmco
KSwKICAgIHBsYXRmb3JtOiAgJ25vZGUnLAogICAgbGV2ZWw6ICAgICAnZXJyb3InLAogICAgcmVs
ZWFzZTogICBSRUxFQVNFLAogICAgZW52aXJvbm1lbnQ6IEVOViwKICAgIHNlcnZlcl9uYW1lOiBT
RVJWSUNFLAogICAgZXhjZXB0aW9uOiB7CiAgICAgIHZhbHVlczogW3sKICAgICAgICB0eXBlOiAg
ZS5uYW1lLAogICAgICAgIHZhbHVlOiBlLm1lc3NhZ2UsCiAgICAgICAgc3RhY2t0cmFjZTogZS5z
dGFjayA/IHsgZnJhbWVzOiBwYXJzZVN0YWNrKGUuc3RhY2spIH0gOiB1bmRlZmluZWQsCiAgICAg
IH1dLAogICAgfSwKICAgIGV4dHJhOiBjb250ZXh0ID8/IHt9LAogIH0KCiAgY29uc3QgYXV0aCA9
CiAgICBgU2VudHJ5IHNlbnRyeV92ZXJzaW9uPTcsIHNlbnRyeV9jbGllbnQ9bmV4dW0tdGhpbi8x
LjAsIGAgKwogICAgYHNlbnRyeV9rZXk9JHtEU04ucHVibGljS2V5fWAKCiAgLy8gTm9kZSAxOCsg
aGFzIGdsb2JhbCBmZXRjaC4gRG8gbm90IGF3YWl0IC0gY2FwdHVyZSBtdXN0IG5vdCBibG9jay4K
ICBmZXRjaChEU04uZW5kcG9pbnQsIHsKICAgIG1ldGhvZDogICdQT1NUJywKICAgIGhlYWRlcnM6
IHsgJ0NvbnRlbnQtVHlwZSc6ICdhcHBsaWNhdGlvbi9qc29uJywgJ1gtU2VudHJ5LUF1dGgnOiBh
dXRoIH0sCiAgICBib2R5OiAgICBKU09OLnN0cmluZ2lmeShldmVudCksCiAgfSkuY2F0Y2goKCkg
PT4gewogICAgLy8gSWYgU2VudHJ5IGl0c2VsZiBpcyB1bnJlYWNoYWJsZSB3ZSBhbHJlYWR5IGxv
Z2dlZCB0aGUgZXJyb3IgYWJvdmU7IHRoZXJlCiAgICAvLyBpcyBub3RoaW5nIG1vcmUgdXNlZnVs
IHRvIGRvIHRoYW4gc3dhbGxvdyB0aGUgcmVwb3J0aW5nIGZhaWx1cmUuCiAgfSkKfQoKLy8gVHVy
biBhIFY4IHN0YWNrIHN0cmluZyBpbnRvIFNlbnRyeSBmcmFtZXMgKGJlc3QtZWZmb3J0OyBTZW50
cnkgaXMgdG9sZXJhbnQgb2YKLy8gYSBwYXJ0aWFsIHN0YWNrdHJhY2UsIGFuZCB3ZSBhbHJlYWR5
IGNhcnJ5IHRoZSByYXcgc3RhY2sgaW4gdGhlIGxvZykuCmZ1bmN0aW9uIHBhcnNlU3RhY2soc3Rh
Y2s6IHN0cmluZyk6IEFycmF5PFJlY29yZDxzdHJpbmcsIHVua25vd24+PiB7CiAgY29uc3QgZnJh
bWVzOiBBcnJheTxSZWNvcmQ8c3RyaW5nLCB1bmtub3duPj4gPSBbXQogIGZvciAoY29uc3QgbGlu
ZSBvZiBzdGFjay5zcGxpdCgnXG4nKS5zbGljZSgxKSkgewogICAgY29uc3QgbSA9IC9hdCAoLis/
KSBcKD8oLis/KTooXGQrKTooXGQrKVwpPyQvLmV4ZWMobGluZS50cmltKCkpCiAgICBpZiAobSkg
ewogICAgICBmcmFtZXMucHVzaCh7CiAgICAgICAgZnVuY3Rpb246IG1bMV0sCiAgICAgICAgZmls
ZW5hbWU6IG1bMl0sCiAgICAgICAgbGluZW5vOiAgIE51bWJlcihtWzNdKSwKICAgICAgICBjb2xu
bzogICAgTnVtYmVyKG1bNF0pLAogICAgICB9KQogICAgfQogIH0KICAvLyBTZW50cnkgZXhwZWN0
cyBpbm5lcm1vc3QgZnJhbWUgbGFzdC4KICByZXR1cm4gZnJhbWVzLnJldmVyc2UoKQp9CgovKgog
IEluc3RhbGwgcHJvY2Vzcy1sZXZlbCBoYW5kbGVycyBzbyBhIHJlamVjdGVkIHByb21pc2Ugb3Ig
YSB0aHJvd24gZXJyb3IgdGhhdAogIGVzY2FwZXMgYWxsIGhhbmRsZXJzIGlzIGNhcHR1cmVkIGlu
c3RlYWQgb2Ygc2lsZW50bHkga2lsbGluZyAob3Igc2lsZW50bHkKICBiZWluZyBpZ25vcmVkIGJ5
KSB0aGUgcHJvY2Vzcy4gQ2FsbCBvbmNlIGF0IHN0YXJ0dXAuCiovCmV4cG9ydCBmdW5jdGlvbiBp
bnN0YWxsR2xvYmFsRXJyb3JDYXB0dXJlKCk6IHZvaWQgewogIHByb2Nlc3Mub24oJ3VuaGFuZGxl
ZFJlamVjdGlvbicsIChyZWFzb246IHVua25vd24pID0+IHsKICAgIGNhcHR1cmVFeGNlcHRpb24o
cmVhc29uLCB7IGtpbmQ6ICd1bmhhbmRsZWRSZWplY3Rpb24nIH0pCiAgfSkKICBwcm9jZXNzLm9u
KCd1bmNhdWdodEV4Y2VwdGlvbicsIChlcnI6IEVycm9yKSA9PiB7CiAgICBjYXB0dXJlRXhjZXB0
aW9uKGVyciwgeyBraW5kOiAndW5jYXVnaHRFeGNlcHRpb24nIH0pCiAgICAvLyBBbiB1bmNhdWdo
dCBleGNlcHRpb24gbGVhdmVzIHRoZSBwcm9jZXNzIGluIGFuIHVuZGVmaW5lZCBzdGF0ZS4gV2Ug
aGF2ZQogICAgLy8gcmVwb3J0ZWQgaXQ7IGxldCB0aGUgcGxhdGZvcm0gcmVzdGFydCB1cyByYXRo
ZXIgdGhhbiBsaW1wIG9uLgogICAgLy8gKEdpdmUgdGhlIGFzeW5jIGNhcHR1cmUgYSBiZWF0IHRv
IGZsdXNoIGJlZm9yZSBleGl0aW5nLikKICAgIHNldFRpbWVvdXQoKCkgPT4gcHJvY2Vzcy5leGl0
KDEpLCAyNTApCiAgfSkKICBsb2cuaW5mbygnZ2xvYmFsIGVycm9yIGNhcHR1cmUgaW5zdGFsbGVk
JywgewogICAgc2VudHJ5OiBEU04gPyAnZW5hYmxlZCcgOiAnZGlzYWJsZWQnLAogIH0pCn0K
B64LOG
base64 -d > "$TTEST" <<'B64TEST'
aW1wb3J0IHsgZGVzY3JpYmUsIGl0LCBleHBlY3QsIHZpLCBiZWZvcmVFYWNoLCBhZnRlckVhY2gg
fSBmcm9tICd2aXRlc3QnCgovLyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Ci8vIFN0cnVjdHVyZWQgbG9n
Z2VyICsgdGhpbiBTZW50cnkgY2FwdHVyZSAoUGhhc2UgNyBIYXJkZW5pbmcpLgovLwovLyBUaGUg
d2hvbGUgcG9pbnQgb2YgdGhpcyBtb2R1bGUgaXMgdGhhdCBmYWlsdXJlcyBzdG9wIGJlaW5nIGxv
c3QsIHNvIHRoZSB0ZXN0cwovLyBhc3NlcnQgZXhhY3RseSB0aGF0OiBldmVyeSBjYXB0dXJlIGlz
IGxvZ2dlZCAod2l0aCBubyBEU04pLCBhIERTTiB0dXJucyBvbiBhbgovLyBIVFRQIHNoaXAsIGFu
ZCBjYXB0dXJlIG5ldmVyIHRocm93cyAtIGJlY2F1c2UgYW4gZXJyb3IgcmVwb3J0ZXIgdGhhdCBj
YW4KLy8gaXRzZWxmIHRocm93IHdvdWxkIGRlZmVhdCBpdHMgb3duIHB1cnBvc2UgaW5zaWRlIGEg
Y2F0Y2ggYmxvY2suCi8vID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KCmRlc2NyaWJlKCdsb2dnZXInLCAo
KSA9PiB7CiAgY29uc3Qgc2F2ZWRFbnYgPSB7IC4uLnByb2Nlc3MuZW52IH0KCiAgYmVmb3JlRWFj
aCgoKSA9PiB7CiAgICB2aS5yZXNldE1vZHVsZXMoKQogICAgZGVsZXRlIHByb2Nlc3MuZW52LlNF
TlRSWV9EU04KICAgIHByb2Nlc3MuZW52LkxPR19MRVZFTCA9ICdkZWJ1ZycKICB9KQogIGFmdGVy
RWFjaCgoKSA9PiB7CiAgICBwcm9jZXNzLmVudiA9IHsgLi4uc2F2ZWRFbnYgfQogICAgdmkucmVz
dG9yZUFsbE1vY2tzKCkKICB9KQoKICBpdCgnZW1pdHMgc3RydWN0dXJlZCBKU09OIHdpdGggbGV2
ZWwsIHNlcnZpY2UgYW5kIG1lc3NhZ2UnLCBhc3luYyAoKSA9PiB7CiAgICBjb25zdCBzcHkgPSB2
aS5zcHlPbihjb25zb2xlLCAnbG9nJykubW9ja0ltcGxlbWVudGF0aW9uKCgpID0+IHt9KQogICAg
Y29uc3QgeyBsb2cgfSA9IGF3YWl0IGltcG9ydCgnLi4vc3JjL2xpYi9sb2dnZXInKQogICAgbG9n
LmluZm8oJ2hlbGxvJywgeyBmb286ICdiYXInIH0pCiAgICBleHBlY3Qoc3B5KS50b0hhdmVCZWVu
Q2FsbGVkVGltZXMoMSkKICAgIGNvbnN0IHBhcnNlZCA9IEpTT04ucGFyc2Uoc3B5Lm1vY2suY2Fs
bHNbMF1bMF0gYXMgc3RyaW5nKQogICAgZXhwZWN0KHBhcnNlZC5sZXZlbCkudG9CZSgnaW5mbycp
CiAgICBleHBlY3QocGFyc2VkLnNlcnZpY2UpLnRvQmUoJ25leHVtLWFwaScpCiAgICBleHBlY3Qo
cGFyc2VkLm1zZykudG9CZSgnaGVsbG8nKQogICAgZXhwZWN0KHBhcnNlZC5mb28pLnRvQmUoJ2Jh
cicpCiAgICBleHBlY3QodHlwZW9mIHBhcnNlZC50cykudG9CZSgnc3RyaW5nJykKICB9KQoKICBp
dCgncmVzcGVjdHMgTE9HX0xFVkVMIChkZWJ1ZyBzdXBwcmVzc2VkIHdoZW4gbGV2ZWwgaXMgaW5m
byknLCBhc3luYyAoKSA9PiB7CiAgICBwcm9jZXNzLmVudi5MT0dfTEVWRUwgPSAnaW5mbycKICAg
IGNvbnN0IHNweSA9IHZpLnNweU9uKGNvbnNvbGUsICdsb2cnKS5tb2NrSW1wbGVtZW50YXRpb24o
KCkgPT4ge30pCiAgICBjb25zdCB7IGxvZyB9ID0gYXdhaXQgaW1wb3J0KCcuLi9zcmMvbGliL2xv
Z2dlcicpCiAgICBsb2cuZGVidWcoJ3Nob3VsZCBiZSBoaWRkZW4nKQogICAgZXhwZWN0KHNweSku
bm90LnRvSGF2ZUJlZW5DYWxsZWQoKQogIH0pCgogIGl0KCdyb3V0ZXMgd2Fybi9lcnJvciB0byBz
dGRlcnInLCBhc3luYyAoKSA9PiB7CiAgICBjb25zdCBlcnJTcHkgPSB2aS5zcHlPbihjb25zb2xl
LCAnZXJyb3InKS5tb2NrSW1wbGVtZW50YXRpb24oKCkgPT4ge30pCiAgICBjb25zdCB7IGxvZyB9
ID0gYXdhaXQgaW1wb3J0KCcuLi9zcmMvbGliL2xvZ2dlcicpCiAgICBsb2cuZXJyb3IoJ2Jvb20n
KQogICAgZXhwZWN0KGVyclNweSkudG9IYXZlQmVlbkNhbGxlZFRpbWVzKDEpCiAgICBleHBlY3Qo
SlNPTi5wYXJzZShlcnJTcHkubW9jay5jYWxsc1swXVswXSBhcyBzdHJpbmcpLmxldmVsKS50b0Jl
KCdlcnJvcicpCiAgfSkKCiAgaXQoJ2NhcHR1cmVFeGNlcHRpb24gYWx3YXlzIGxvZ3MgdGhlIGVy
cm9yLCBldmVuIHdpdGggbm8gRFNOJywgYXN5bmMgKCkgPT4gewogICAgY29uc3QgZXJyU3B5ID0g
dmkuc3B5T24oY29uc29sZSwgJ2Vycm9yJykubW9ja0ltcGxlbWVudGF0aW9uKCgpID0+IHt9KQog
ICAgY29uc3QgZmV0Y2hTcHkgPSB2aS5mbigpCiAgICB2aS5zdHViR2xvYmFsKCdmZXRjaCcsIGZl
dGNoU3B5KQogICAgY29uc3QgeyBjYXB0dXJlRXhjZXB0aW9uIH0gPSBhd2FpdCBpbXBvcnQoJy4u
L3NyYy9saWIvbG9nZ2VyJykKICAgIGNhcHR1cmVFeGNlcHRpb24obmV3IEVycm9yKCdrYWJvb20n
KSwgeyBiYXRjaElkOiAnQjEnIH0pCiAgICBleHBlY3QoZXJyU3B5KS50b0hhdmVCZWVuQ2FsbGVk
KCkKICAgIGNvbnN0IHBhcnNlZCA9IEpTT04ucGFyc2UoZXJyU3B5Lm1vY2suY2FsbHNbMF1bMF0g
YXMgc3RyaW5nKQogICAgZXhwZWN0KHBhcnNlZC5tc2cpLnRvQmUoJ2thYm9vbScpCiAgICBleHBl
Y3QocGFyc2VkLmJhdGNoSWQpLnRvQmUoJ0IxJykKICAgIGV4cGVjdChwYXJzZWQuc3RhY2spLnRv
Q29udGFpbignRXJyb3InKQogICAgLy8gTm8gRFNOIC0+IG5vIEhUVFAgc2hpcAogICAgZXhwZWN0
KGZldGNoU3B5KS5ub3QudG9IYXZlQmVlbkNhbGxlZCgpCiAgICB2aS51bnN0dWJBbGxHbG9iYWxz
KCkKICB9KQoKICBpdCgnY2FwdHVyZUV4Y2VwdGlvbiBzaGlwcyB0byBTZW50cnkgd2hlbiBTRU5U
UllfRFNOIGlzIHNldCcsIGFzeW5jICgpID0+IHsKICAgIHByb2Nlc3MuZW52LlNFTlRSWV9EU04g
PSAnaHR0cHM6Ly9hYmMxMjNAbzEuaW5nZXN0LnNlbnRyeS5pby80NTYnCiAgICB2aS5zcHlPbihj
b25zb2xlLCAnZXJyb3InKS5tb2NrSW1wbGVtZW50YXRpb24oKCkgPT4ge30pCiAgICBjb25zdCBm
ZXRjaFNweSA9IHZpLmZuKGFzeW5jICgpID0+ICh7IG9rOiB0cnVlIH0pKQogICAgdmkuc3R1Ykds
b2JhbCgnZmV0Y2gnLCBmZXRjaFNweSBhcyBhbnkpCiAgICBjb25zdCB7IGNhcHR1cmVFeGNlcHRp
b24gfSA9IGF3YWl0IGltcG9ydCgnLi4vc3JjL2xpYi9sb2dnZXInKQogICAgY2FwdHVyZUV4Y2Vw
dGlvbihuZXcgRXJyb3IoJ3NoaXAgbWUnKSkKICAgIC8vIGZldGNoIGlzIGZpcmUtYW5kLWZvcmdl
dDsgZ2l2ZSB0aGUgbWljcm90YXNrIGEgdGljawogICAgYXdhaXQgbmV3IFByb21pc2UociA9PiBz
ZXRUaW1lb3V0KHIsIDApKQogICAgZXhwZWN0KGZldGNoU3B5KS50b0hhdmVCZWVuQ2FsbGVkVGlt
ZXMoMSkKICAgIGNvbnN0IFt1cmwsIG9wdHNdID0gZmV0Y2hTcHkubW9jay5jYWxsc1swXQogICAg
ZXhwZWN0KFN0cmluZyh1cmwpKS50b0JlKCdodHRwczovL28xLmluZ2VzdC5zZW50cnkuaW8vYXBp
LzQ1Ni9zdG9yZS8nKQogICAgZXhwZWN0KChvcHRzIGFzIGFueSkuaGVhZGVyc1snWC1TZW50cnkt
QXV0aCddKS50b0NvbnRhaW4oJ3NlbnRyeV9rZXk9YWJjMTIzJykKICAgIHZpLnVuc3R1YkFsbEds
b2JhbHMoKQogIH0pCgogIGl0KCdjYXB0dXJlRXhjZXB0aW9uIG5ldmVyIHRocm93cywgZXZlbiBv
biBhIGJyb2tlbiBEU04gb3IgYmFkIGZldGNoJywgYXN5bmMgKCkgPT4gewogICAgcHJvY2Vzcy5l
bnYuU0VOVFJZX0RTTiA9ICdub3QtYS12YWxpZC1kc24nCiAgICB2aS5zcHlPbihjb25zb2xlLCAn
ZXJyb3InKS5tb2NrSW1wbGVtZW50YXRpb24oKCkgPT4ge30pCiAgICB2aS5zdHViR2xvYmFsKCdm
ZXRjaCcsICgpID0+IHsgdGhyb3cgbmV3IEVycm9yKCduZXR3b3JrIGV4cGxvZGVkJykgfSkKICAg
IGNvbnN0IHsgY2FwdHVyZUV4Y2VwdGlvbiB9ID0gYXdhaXQgaW1wb3J0KCcuLi9zcmMvbGliL2xv
Z2dlcicpCiAgICBleHBlY3QoKCkgPT4gY2FwdHVyZUV4Y2VwdGlvbihuZXcgRXJyb3IoJ3gnKSkp
Lm5vdC50b1Rocm93KCkKICAgIHZpLnVuc3R1YkFsbEdsb2JhbHMoKQogIH0pCgogIGl0KCdhY2Nl
cHRzIGEgbm9uLUVycm9yIHZhbHVlIHdpdGhvdXQgdGhyb3dpbmcnLCBhc3luYyAoKSA9PiB7CiAg
ICB2aS5zcHlPbihjb25zb2xlLCAnZXJyb3InKS5tb2NrSW1wbGVtZW50YXRpb24oKCkgPT4ge30p
CiAgICBjb25zdCB7IGNhcHR1cmVFeGNlcHRpb24gfSA9IGF3YWl0IGltcG9ydCgnLi4vc3JjL2xp
Yi9sb2dnZXInKQogICAgZXhwZWN0KCgpID0+IGNhcHR1cmVFeGNlcHRpb24oJ2p1c3QgYSBzdHJp
bmcnKSkubm90LnRvVGhyb3coKQogIH0pCn0pCg==
B64TEST
base64 -d > "$TPATCH" <<'B64PATCH'
IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwoiIiIKUGhhc2UgNyBQYXJ0IDMgLSB3aXJlIHN0cnVjdHVy
ZWQgbG9nZ2luZyArIFNlbnRyeSBjYXB0dXJlIGludG8gdGhlIEFQSS4KCkVkaXRzOgogIHNyYy9t
aWRkbGV3YXJlL2Vycm9ySGFuZGxlci50cwogICAgKiBjYXB0dXJlIHVuaGFuZGxlZCByb3V0ZSBl
cnJvcnMgKHdpdGggc3RhY2sgKyByZXF1ZXN0IGNvbnRleHQpIGluc3RlYWQgb2YKICAgICAgbG9n
Z2luZyBqdXN0IHRoZSBtZXNzYWdlCiAgc3JjL2luZGV4LnRzCiAgICAqIGluc3RhbGwgcHJvY2Vz
cy1sZXZlbCBoYW5kbGVycyAodW5oYW5kbGVkUmVqZWN0aW9uIC8gdW5jYXVnaHRFeGNlcHRpb24p
CiAgICAgIGF0IHN0YXJ0dXAKICBzcmMvcm91dGVzL3BheXJvbGwudHMKICAgICogdGhlIGZpcmUt
YW5kLWZvcmdldCBydW5CYXRjaFBheW91dCguLi4pLmNhdGNoKCgpID0+IHt9KSBjdXJyZW50bHkg
c3dhbGxvd3MKICAgICAgYSB3aG9sZSBmYWlsZWQgcGF5b3V0IHJ1biAtIGNhcHR1cmUgaXQgaW5z
dGVhZAoKSWRlbXBvdGVudCB2aWEgX19ORVhVTV9PQlNFUlZBQklMSVRZX1dJUkVEX18uIEV4YWN0
LWFuY2hvcjsgYWJvcnRzIG9uIGRyaWZ0LgoiIiIKaW1wb3J0IHN5cywgaW8KCmRlZiBwYXRjaChw
YXRoLCBlZGl0cywgbWFya2VyKToKICAgIHNyYyA9IGlvLm9wZW4ocGF0aCwgZW5jb2Rpbmc9InV0
Zi04IikucmVhZCgpCiAgICBpZiBtYXJrZXIgaW4gc3JjOgogICAgICAgIHByaW50KGYiICB7cGF0
aH06IGFscmVhZHkgd2lyZWQgLSBza2lwcGluZy4iKQogICAgICAgIHJldHVybgogICAgZm9yIGRl
c2MsIG9sZCwgbmV3IGluIGVkaXRzOgogICAgICAgIG4gPSBzcmMuY291bnQob2xkKQogICAgICAg
IGlmIG4gIT0gMToKICAgICAgICAgICAgcHJpbnQoZiJFUlJPUiBbe3BhdGh9XTogYW5jaG9yICd7
ZGVzY30nIG1hdGNoZWQge259IHRpbWVzIChleHBlY3RlZCAxKS4gQWJvcnRpbmcuIikKICAgICAg
ICAgICAgc3lzLmV4aXQoMikKICAgICAgICBzcmMgPSBzcmMucmVwbGFjZShvbGQsIG5ldykKICAg
IGlvLm9wZW4ocGF0aCwgInciLCBlbmNvZGluZz0idXRmLTgiKS53cml0ZShzcmMpCiAgICBwcmlu
dChmIiAge3BhdGh9OiB3aXJlZC4iKQoKTUFSS0VSID0gIl9fTkVYVU1fT0JTRVJWQUJJTElUWV9X
SVJFRF9fIgoKIyAtLS0tIGVycm9ySGFuZGxlci50cyA6IHJlcGxhY2UgdGhlIHdob2xlIGJvZHkg
LS0tLQpwYXRjaCgibmV4dW0tYXBpL3NyYy9taWRkbGV3YXJlL2Vycm9ySGFuZGxlci50cyIsIFsK
ICAgICgid2hvbGUgZmlsZSIsCiAgICAgImltcG9ydCB0eXBlIHsgUmVxdWVzdCwgUmVzcG9uc2Us
IE5leHRGdW5jdGlvbiB9IGZyb20gJ2V4cHJlc3MnXG5cbmV4cG9ydCBmdW5jdGlvbiBlcnJvckhh
bmRsZXIoZXJyOiBFcnJvciwgX3JlcTogUmVxdWVzdCwgcmVzOiBSZXNwb25zZSwgX25leHQ6IE5l
eHRGdW5jdGlvbikge1xuICBjb25zb2xlLmVycm9yKCdbRXJyb3JdJywgZXJyLm1lc3NhZ2UpXG4g
IHJlcy5zdGF0dXMoNTAwKS5qc29uKHsgZXJyb3I6ICdJbnRlcm5hbCBzZXJ2ZXIgZXJyb3InLCBt
ZXNzYWdlOiBlcnIubWVzc2FnZSB9KVxufSIsCiAgICAgImltcG9ydCB0eXBlIHsgUmVxdWVzdCwg
UmVzcG9uc2UsIE5leHRGdW5jdGlvbiB9IGZyb20gJ2V4cHJlc3MnXG4iCiAgICAgIi8vIF9fTkVY
VU1fT0JTRVJWQUJJTElUWV9XSVJFRF9fIChwaGFzZTcpIGNhcHR1cmUgdW5oYW5kbGVkIHJvdXRl
IGVycm9yc1xuIgogICAgICJpbXBvcnQgeyBjYXB0dXJlRXhjZXB0aW9uIH0gZnJvbSAnLi4vbGli
L2xvZ2dlcidcblxuIgogICAgICJleHBvcnQgZnVuY3Rpb24gZXJyb3JIYW5kbGVyKGVycjogRXJy
b3IsIHJlcTogUmVxdWVzdCwgcmVzOiBSZXNwb25zZSwgX25leHQ6IE5leHRGdW5jdGlvbikge1xu
IgogICAgICIgIC8vIENhcHR1cmUgd2l0aCByZXF1ZXN0IGNvbnRleHQgKG1ldGhvZCArIHBhdGgs
IG5ldmVyIHRoZSBib2R5IC0gaXQgbWF5XG4iCiAgICAgIiAgLy8gaG9sZCBQSUkvYW1vdW50cyku
IFRoaXMgbG9ncyBzdHJ1Y3R1cmVkIEpTT04gQU5EIHNoaXBzIHRvIFNlbnRyeSB3aGVuXG4iCiAg
ICAgIiAgLy8gU0VOVFJZX0RTTiBpcyBzZXQsIHNvIGFuIHVuaGFuZGxlZCByb3V0ZSBlcnJvciBp
cyBuZXZlciBsb3N0LlxuIgogICAgICIgIGNhcHR1cmVFeGNlcHRpb24oZXJyLCB7IHNjb3BlOiAn
cm91dGUnLCBtZXRob2Q6IHJlcS5tZXRob2QsIHBhdGg6IHJlcS5wYXRoIH0pXG4iCiAgICAgIiAg
cmVzLnN0YXR1cyg1MDApLmpzb24oeyBlcnJvcjogJ0ludGVybmFsIHNlcnZlciBlcnJvcicsIG1l
c3NhZ2U6IGVyci5tZXNzYWdlIH0pXG4iCiAgICAgIn0iKSwKXSwgTUFSS0VSKQoKIyAtLS0tIGlu
ZGV4LnRzIDogaW5zdGFsbCBnbG9iYWwgY2FwdHVyZSBuZWFyIHRoZSB0b3Agb2Ygc3RhcnR1cCAt
LS0tCnBhdGNoKCJuZXh1bS1hcGkvc3JjL2luZGV4LnRzIiwgWwogICAgKCJpbXBvcnQiLAogICAg
ICJpbXBvcnQgeyBlcnJvckhhbmRsZXIgfSAgICAgICAgICAgZnJvbSAnLi9taWRkbGV3YXJlL2Vy
cm9ySGFuZGxlciciLAogICAgICJpbXBvcnQgeyBlcnJvckhhbmRsZXIgfSAgICAgICAgICAgZnJv
bSAnLi9taWRkbGV3YXJlL2Vycm9ySGFuZGxlcidcbiIKICAgICAiLy8gX19ORVhVTV9PQlNFUlZB
QklMSVRZX1dJUkVEX18gKHBoYXNlNylcbiIKICAgICAiaW1wb3J0IHsgaW5zdGFsbEdsb2JhbEVy
cm9yQ2FwdHVyZSwgbG9nIH0gZnJvbSAnLi9saWIvbG9nZ2VyJyIpLAogICAgKCJpbnN0YWxsIGJl
Zm9yZSBhcHAiLAogICAgICJjb25zdCBhcHAgID0gZXhwcmVzcygpIiwKICAgICAiaW5zdGFsbEds
b2JhbEVycm9yQ2FwdHVyZSgpXG5jb25zdCBhcHAgID0gZXhwcmVzcygpIiksCl0sIE1BUktFUikK
CiMgLS0tLSBwYXlyb2xsLnRzIDogY2FwdHVyZSB0aGUgc3dhbGxvd2VkIHBheW91dCBydW4gLS0t
LQpwYXRjaCgibmV4dW0tYXBpL3NyYy9yb3V0ZXMvcGF5cm9sbC50cyIsIFsKICAgICgiaW1wb3J0
IiwKICAgICAiaW1wb3J0IHsgcmFuZG9tVVVJRCwgY3JlYXRlSGFzaCB9IGZyb20gJ2NyeXB0bycg
IC8vIFBIQVNFXzdGOiBjcmVhdGVIYXNoIGZvciBkZXRlcm1pbmlzdGljIGlkZW1wb3RlbmN5IFVV
SUQiLAogICAgICJpbXBvcnQgeyByYW5kb21VVUlELCBjcmVhdGVIYXNoIH0gZnJvbSAnY3J5cHRv
JyAgLy8gUEhBU0VfN0Y6IGNyZWF0ZUhhc2ggZm9yIGRldGVybWluaXN0aWMgaWRlbXBvdGVuY3kg
VVVJRFxuIgogICAgICIvLyBfX05FWFVNX09CU0VSVkFCSUxJVFlfV0lSRURfXyAocGhhc2U3KSBz
dXJmYWNlIHN3YWxsb3dlZCBwYXlvdXQgZmFpbHVyZXNcbiIKICAgICAiaW1wb3J0IHsgY2FwdHVy
ZUV4Y2VwdGlvbiB9IGZyb20gJy4uL2xpYi9sb2dnZXInIiksCiAgICAoInJ1bkJhdGNoUGF5b3V0
IGNhdGNoIiwKICAgICAiICAgIHJ1bkJhdGNoUGF5b3V0KGJhdGNoSWQpLmNhdGNoKCgpID0+IHt9
KSIsCiAgICAgIiAgICBydW5CYXRjaFBheW91dChiYXRjaElkKS5jYXRjaChlcnIgPT5cbiAgICAg
IGNhcHR1cmVFeGNlcHRpb24oZXJyLCB7IHNjb3BlOiAncGF5cm9sbC5ydW5CYXRjaFBheW91dCcs
IGJhdGNoSWQgfSkpIiksCl0sIE1BUktFUikKCnByaW50KCJPYnNlcnZhYmlsaXR5IHdpcmluZyBj
b21wbGV0ZS4iKQo=
B64PATCH

verify(){ local got; got="$( (sha256sum "$1" 2>/dev/null || shasum -a 256 "$1") | awk '{print $1}')"; [ "$got" = "$2" ] || die "Checksum mismatch for $1 (got $got). Nothing written."; }
verify "$TLOG" "$LOG_SHA"; verify "$TTEST" "$TEST_SHA"; verify "$TPATCH" "$PATCH_SHA"
log "All payloads verified."

mkdir -p "$BACKUP_DIR"
for f in "$EH:errorHandler.ts" "$IDX:index.ts" "$PAYROLL:payroll.ts"; do
  src="${f%%:*}"; name="${f##*:}"
  if [ -f "$src" ] && ! grep -qF "$MARKER" "$src"; then cp "$src" "$BACKUP_DIR/$name"; fi
done

mkdir -p "$API/src/lib" "$API/tests"
if [ -f "$LOGGER" ]; then log "logger already present - leaving it."; else cp "$TLOG" "$LOGGER"; log "Added $LOGGER"; fi
if [ -f "$LOGGER_TEST" ]; then log "logger test already present - leaving it."; else cp "$TTEST" "$LOGGER_TEST"; log "Added $LOGGER_TEST"; fi

python3 "$TPATCH" || {
  for f in "$EH:errorHandler.ts" "$IDX:index.ts" "$PAYROLL:payroll.ts"; do
    src="${f%%:*}"; name="${f##*:}"
    [ -f "$BACKUP_DIR/$name" ] && cp "$BACKUP_DIR/$name" "$src"
  done
  die "Wiring failed; patched files restored."
}

log ""
log "=== Gate: tsc + tests ==="
( cd "$API" && npx tsc --noEmit ) || die "API tsc failed - not committing."
log "tsc clean."
( cd "$API" && npx vitest run ) || die "API tests failed - not committing."
log "tests pass."

if [ "$FLAG" = "--no-deploy" ]; then
  log "--no-deploy: applied + verified. Rerun without the flag to commit + push."
  log "Set SENTRY_DSN in prod env to enable Sentry shipping (inert until then)."
  exit 0
fi

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "Not a git work tree; commit manually."
REMOTE="$(git remote | head -1 || true)"; [ -n "$REMOTE" ] || die "No git remote; commit/push manually."
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
git add -A
if git diff --cached --quiet; then log "Nothing to commit."; exit 0; fi
log "Committing on '$BRANCH' -> '$REMOTE'..."
git commit -m "$COMMIT_MSG"
git push "$REMOTE" "$BRANCH"
log ""
log "Pushed Phase 7 Part 3. Set SENTRY_DSN in prod to turn on error shipping."
log "Adopt log.* / captureException incrementally in place of console.* + silent catches."
